language: node_js
cache:
  directories:
    - "node_modules"

# See: https://github.com/nodejs/Release
node_js:
  - "node" # Latest node version
  - "8"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
- npm run test
after_script:
- npm run report-coverage
